### ISSUE TITLE
Unsupported CIGAR token: '40H'.

### ISSUE THREAD

**Issue by davidchampredon** [PoonLab/sam2conseq#19]
@ArtPoon : A run on a SAM file generates the error message:

> Traceback (most recent call last):
  File "sam2conseq.py", line 553, in <module>
    main()
  File "sam2conseq.py", line 536, in main
    res = sam2freq(args.samfile, unpaired=args.unpaired)
  File "sam2conseq.py", line 377, in sam2freq
    for rname, mseq, insert_list, failed_list in itr:
  File "sam2conseq.py", line 297, in parse_sam
    seq1, qual1, inserts = apply_cigar(cigar1, row1['seq'], row1['qual'], pos1)
  File "sam2conseq.py", line 92, in apply_cigar
    'Unsupported CIGAR token: {!r}.'.format(''.join(token))
RuntimeError: Unsupported CIGAR token: '40H'.

Grepping `40H` in the SAM file returns (I deleted all the non-CIGAR related lines): 

```49a765d8-0950-4aa1-bb9c-b20652c232f4	2064	MN908947.3	4506	60	351H23M1D5M2I12M1I14M3I32M1D3M1D44M1D47M40H	*	0	0	GTGTGGTTGATTATGGTGCTAGATTTACTTTTTTACACCAGTAAAAACAACTGTAGCGCTGTCACCCATCAACACACTTAACGATCTAAATGGTCCTTGTTACAATGCCACTTGGCTATGTAACACATGGCTTAAATTTGAAGAAGTTGCTCGGTATATGAGATCTCTCAAAGTGCCAGCTACAGT	A=A@;;<9?:A>I@>;@@ECC?<7'&%(*+-3=9:8?68879;?@401>E<77<33)''$%*1*/---;>869.@@@IIEE4A?>B>>B?74$(058.55389:CFDB8=62647994++7B?@:?>@BC9F?FHFC@;@:G7*))(&23%%;>15=D;@???;6,$&BEKID@?@?;7(7'*..2	NM:i:15	ms:i:282	AS:i:282	nn:i:0	tp:A:P	cm:i:13	s1:i:119	s2:i:0	de:f:0.0642	SA:Z:MN908947.3,5684,+,255S273M2D49S,60,21;	rl:i:0
c6b5c35c-46a2-4bef-b00a-e5e194da1bf3	2064	MN908947.3	8125	60	329H67M2I21M1I129M40H	*	0	0	TGCAAAGAATGTGTCCTTAGACAATGTCTTATCTACTTTTATTTCAGCAGCTCGGCAAGGGCTTGTTGGGATTCAGATGCAGAAACTAAAGGATGCTGTTGAATGTCTTAAATTGTCACATCAATCTGACATAGAAGTTACTGGCGATAGTTGTAATAACTATATGCTCACCTATAACAAAGTTGAAAACATGACACCCCGTGACCTTGGTGCTTGTATT	6('-+(*-)%$#$$+-7.99=@@B@CAFQHIFDJGB<CIG@HJHCFAEGIE=>BC:022<>.FD@)'>>''A3*&,$&$%.27@,?,<*$*$$,&$&%*1====;?CD;>A?A?>>A>?CDDA@438:@76<74<;;98ELA@?<?=C>6:<:5)$6>?CDFDCEAC10/43539B@77;88AC?6FAAA@CA?A>?F<689BB=;AB59AF@AA95&22	NM:i:6	ms:i:402	AS:i:402	nn:i:0	tp:A:P	cm:i:25	s1:i:174	s2:i:0	de:f:0.0228	SA:Z:MN908947.3,7421,+,251S274M13I51S,60,17;	rl:i:0
99133bb6-c9e2-48b4-bcd5-6da2ff368131	2048	MN908947.3	31	60	40H100M1D10M1D15M285H	*	0	0	ACCAGCCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAACGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACTCACGCAGTATATTATCAACTAGTACTGTCGTTGAC	<8-;$26%'6667/@A?=>CEB7/00=:=A>BB:)?*=><---<2221;8A:5;;?7@4=@>>1*+%&+589:D:7=<-3:;%'9*;=ACA7/-((),*&&*)$%%''%$%%13:=:8<;F5=9%	NM:i:6	ms:i:214	AS:i:214	nn:i:0	tp:A:P	cm:i:16	s1:i:90	s2:i:0	de:f:0.0472	SA:Z:MN908947.3,28082,-,55S169M1D226S,60,14;	rl:i:0
2121d737-e1db-476b-92fe-22e99582e3e3	2048	MN908947.3	17065	60	40H35M1D1M1D15M1D10M1D64M1I5M2I2M2D16M226H	*	0	0	TATTCTACACTCCAGGGACCACCTGGTACTGGTAAATCATTTTGCTATTGGCTAGCTCTCTCTACTATTCTGCTCGCATAGTGTATACAGCTTGCTCTCATGCCGCTGTTGATGCACTATGTGAGAAACGCTGATAAATATTTGCCTATAG	6339C?BAGBF)A>??FG8;8GGGHD3%69:><73&6:>EHO3B@?AAA991'$)9;84+/9976'$%)1444041=6>?CAC<==FAG=AD@=BD=5?CCGEEFEKBHF?;?>77:667;66301+$$%#$)'--.30.98;-443+$$%	NM:i:12	ms:i:232	AS:i:232	nn:i:0	tp:A:P	cm:i:12	s1:i:86	s2:i:0	de:f:0.0645	SA:Z:MN908947.3,16028,+,185S179M4D53S,60,10;	rl:i:0
03178bbd-0a6b-4256-99f3-f152dd2ec9b9	2048	MN908947.3	27142	11	40H12M1D35M1D27M407H	*	0	0	ACACAGACCATTCAGTAGCAGTGACAATATTGCTTTGCTTGTACAGTAGTGACAACAGATGTTTCATCTCGTTG	<71)))<=ABC>>7BBHA==B>>'+0/****0()*2''++:<844?*;(:?:851+++$&&-/0396793/0+-	NM:i:2	ms:i:136	AS:i:136	nn:i:0	tp:A:P	cm:i:6	s1:i:47	s2:i:0	de:f:0.0263	SA:Z:MN908947.3,26836,-,47S342M6I126S,60,44;	rl:i:0
d14a0e2b-aff6-4e0e-85ca-21a1471f7739	2048	MN908947.3	28395	60	40H59M1D51M262H	*	0	0	GGCCCCAAGGTTTACCCAATAATACTGCGTCTTGGTTCACCGCTCTCACTCAACATGGCAGGAAGACCTTAAATTCCCTCGAGGACAAGGCGTTCCAGTTAACACCAATA	B=RKDBAB5>FH84354...:8=BCGBD?>:IFC;EH?<CA?>C<4@:;7D34<BAA5).57$0C>8<>??A;;210.)66=:=1.#&'(#,97&(%$3;:;;A@AA@<=	NM:i:2	ms:i:208	AS:i:208	nn:i:0	tp:A:P	cm:i:15	s1:i:95	s2:i:0	de:f:0.018	SA:Z:MN908947.3,12047,+,149S210M2I51S,60,8;	rl:i:0
e0702436-2f79-4eb5-b085-fae781f407fb	2048	MN908947.3	28395	60	40H9M1I1M1I40M1I11M1I17M2I17M1D15M258H	*	0	0	GGCCCCAAGAGTTTTACCCAATAATACTGCGTCTTGGTTCACCGCTCTCACTCCAACATGGCAAGGGAAGACCTTAAATTCCCACTCGAGGACAAGGCGTTCAATTAACACCAATA	67:555/8/(?*CG@66@A67@:@>AAF>BE@4/.33A>@9E?8:B:/-'(($+)*--/0-)**$$,1:9=.555=?FJG:A4%#&(.17;F?CBC:99D/?9<>D;2''':9;>3	NM:i:7	ms:i:182	AS:i:182	nn:i:0	tp:A:P	cm:i:7	s1:i:84	s2:i:0	de:f:0.0517	SA:Z:MN908947.3,12047,+,155S203M3D56S,60,13;	rl:i:0
c467d4bd-54ec-4542-a6a3-ec1df719df82	2048	MN908947.3	28395	60	40H54M3I5M1D51M267H	*	0	0	GGCCCCAAGGTTTACCCAATAATACTGCGTCTTGGTTCACCGCTCTCACTCAACTTTGTGGCAGGAAGACCTTAAATTCCCTCGAGGACAAGGCGTTCCAATTAACACCAATA	B>;6777>??DK944?>:;91867<<>:;9:5578B=<7;;AE8-/9997:%&$%%%$'&%#%&/.58557668<AJHED78>04:C@?>:5-21;<+:8<87?@AI@?FF?/	NM:i:5	ms:i:198	AS:i:198	nn:i:0	tp:A:P	cm:i:14	s1:i:94	s2:i:0	de:f:0.0268	SA:Z:MN908947.3,12047,+,152S210M3I55S,60,7;	rl:i:0```

**Comment by ArtPoon** [comment]
Ok I'm going to work on this in PoonLab/sup
This is a hard clip and I think it's an easy fix...

**Comment by ArtPoon** [comment]
Can you please send me the accession number of the BAM file you're processing so I can reproduce?
